server:
  port: 8081

spring:
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      clientAuthenticationScheme: form
      preEstablishedRedirectUri:
      useCurrentUri: false
    resource:
        userInfoUri: https://api.github.com/user