spring:
  application:
    name: spring-cloud-zuul-apigateway
server:
  port: 8080
zuul:
  routes:
    test1:
      path: /test1/**
      url: http://localhost:8081
      sensitiveHeaders:
    test2:
      path: /test2/**
      url: http://localhost:8082
      sensitiveHeaders:
    login:
      path: /login/**
      url: http://localhost:8083
      sensitiveHeaders: