server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    hikari:
      minimum-idle: 30
  jpa:
    show-sql: true
#    open-in-view: false
    hibernate:
      ddl-auto: create
