server:
  port: 8080

logging:
  level:
    root: TRACE
    org:
      apache: INFO

zuul:
  routes:
    auth:
      sensitiveHeaders:
      url: http://localhost:19000
    oauth:
      sensitiveHeaders:
      url: http://localhost:19000/oauth

security:
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      tokenName: oauth_token
      authenticationScheme: form
      clientAuthenticationScheme: form
      preEstablishedRedirectUri:
      useCurrentUri: true
    sso:
      loginPath: /login
    resource:
      token-info-uri: http://localhost:8080/auth/oauth/check_token