server:
  port: 8081
  servlet.session.cookie.name : SPRINGJSESSIONID

spring:
  thymeleaf:
    cache: false

logging.level.root: INFO

security:
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      tokenName: oauth_token
      authenticationScheme: form
      clientAuthenticationScheme: form
      preEstablishedRedirectUri:
      useCurrentUri: true
    sso:
      loginPath: /login
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token

zuul:
  routes:
    auth:
      url=http://localhost:8080