server:
  port: 8080

logging:
  level:
    root: TRACE
    org:
      apache: INFO

zuul:
  routes:
    auth:
      sensitiveHeaders:
      url: http://localhost:8081/auth
    resource1:
      sensitiveHeaders:
      url: http://localhost:8082
  addProxyHeaders: true

security:
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://localhost:8080/auth/oauth/token
      userAuthorizationUri: http://localhost:8080/auth/oauth/authorize
      tokenName: oauth_token
      authenticationScheme: form
      clientAuthenticationScheme: form
      preEstablishedRedirectUri:
      useCurrentUri: true
    sso:
      loginPath: /login
    resource:
      jwt:
        key-value: testing